package com.example.kokoro82m.screens

import ai.onnxruntime.OrtSession
import android.content.Intent
import android.net.Uri
import androidx.activity.compose.rememberLauncherForActivityResult
import androidx.activity.result.contract.ActivityResultContracts
import androidx.compose.foundation.ExperimentalFoundationApi
import androidx.compose.foundation.background
import androidx.compose.foundation.clickable
import androidx.compose.foundation.combinedClickable
import androidx.compose.foundation.layout.*
import androidx.compose.foundation.lazy.LazyColumn
import androidx.compose.foundation.lazy.itemsIndexed
import androidx.compose.foundation.lazy.rememberLazyListState
import androidx.compose.material.icons.Icons
import androidx.compose.material.icons.filled.ArrowDropDown
import androidx.compose.material3.*
import androidx.compose.runtime.*
import androidx.compose.ui.Alignment
import androidx.compose.ui.Modifier
import androidx.compose.ui.graphics.Color
import androidx.compose.ui.graphics.graphicsLayer
import androidx.compose.ui.platform.LocalContext
import androidx.compose.ui.res.dimensionResource
import androidx.compose.ui.text.style.TextAlign
import androidx.compose.ui.unit.dp
import androidx.lifecycle.viewmodel.compose.viewModel
import com.example.kokoro82m.R
import com.example.kokoro82m.utils.*
import com.example.kokoro82m.ui.components.ProgressDialog
import com.example.kokoro82m.viewmodel.BookViewModel
import kotlinx.coroutines.launch

@OptIn(ExperimentalMaterial3Api::class, ExperimentalLayoutApi::class, ExperimentalFoundationApi::class)
@Composable
fun BookScreen(
    session: OrtSession,
    phonemeConverter: PhonemeConverter,
    bookViewModel: BookViewModel = viewModel()
) {
    val context = LocalContext.current
    val scope = rememberCoroutineScope()

    val lines by bookViewModel.lines.collectAsState()
    val currentLine by bookViewModel.currentLine.collectAsState()
    val playerState by bookViewModel.playerState.collectAsState()

    val bookUri by bookViewModel.bookUri.collectAsState()
    var bookmark by remember { mutableStateOf<Bookmark?>(null) }

    val listState = rememberLazyListState()

    val styleLoader = remember { StyleLoader(context) }
    var selectedStyles by remember { mutableStateOf(listOf("af_sarah")) }
    var weights by remember { mutableStateOf(mapOf("af_sarah" to 1f)) }
    var interpolationMode by remember { mutableStateOf(InterpolationMode.LINEAR) }
    var speed by remember { mutableFloatStateOf(SettingsManager.getSpeed(context)) }
    var debugMessage by remember { mutableStateOf<String?>(null) }
    var isProcessing by remember { mutableStateOf(false) }
    var isPregenerating by remember { mutableStateOf(false) }
    var preGenProgress by remember { mutableFloatStateOf(0f) }

    var showSettings by remember { mutableStateOf(true) }

    var projectName by remember { mutableStateOf("") }
    var usePregenerated by remember { mutableStateOf(false) }
    var projects by remember { mutableStateOf(listOf<Project>()) }
    val selectedLines = remember { mutableStateListOf<Int>() }

    val launcher = rememberLauncherForActivityResult(
        contract = ActivityResultContracts.OpenDocument()
    ) { uri: Uri? ->
        uri?.let {
            // Persist read permission so the URI can be reopened later from saved projects
            context.contentResolver.takePersistableUriPermission(
                it,
                Intent.FLAG_GRANT_READ_URI_PERMISSION
            )
            bookViewModel.loadBook(context, it)
        }
    }

    LaunchedEffect(Unit) {
        projects = ProjectManager.list(context)
    }

    LaunchedEffect(bookUri) {
        bookUri?.let { uri ->
            val project = ProjectManager.load(context, uri.toString())
            if (project != null) {
                selectedStyles = project.styles.ifEmpty { listOf("af_sarah") }
                weights = if (project.weights.isNotEmpty()) project.weights else mapOf("af_sarah" to 1f)
                interpolationMode = project.mode
                speed = project.speed
                bookmark = project.bookmark
                 projectName = project.name
                 usePregenerated = project.usePregenerated
                DebugLogger.log("Loaded project: $project")
                bookViewModel.setCurrentLine(project.bookmark?.line ?: 0)
            } else {
                bookmark = BookmarkManager.load(context, uri.toString())
                DebugLogger.log("Loaded bookmark: $bookmark")
                bookmark?.let { bookViewModel.setCurrentLine(it.line) } ?: bookViewModel.setCurrentLine(0)
            }
            projects = ProjectManager.list(context)
        }
    }

    LaunchedEffect(currentLine) {
        if (currentLine >= 0) {
            listState.animateScrollToItem(currentLine)
        }
    }

    LazyColumn(
        modifier = Modifier
            .fillMaxSize()
            .padding(dimensionResource(id = R.dimen.padding_large)),
        verticalArrangement = Arrangement.spacedBy(dimensionResource(id = R.dimen.padding_medium)),
        state = listState
    ) {
        item {
            Card(modifier = Modifier.fillMaxWidth()) {
                Column(modifier = Modifier.padding(dimensionResource(id = R.dimen.padding_medium))) {
                    Row(
                        modifier = Modifier
                            .fillMaxWidth()
                            .clickable { showSettings = !showSettings },
                        verticalAlignment = Alignment.CenterVertically
                    ) {
                        Text("Settings", style = MaterialTheme.typography.titleMedium)
                        Spacer(modifier = Modifier.weight(1f))
                        Icon(
                            imageVector = Icons.Default.ArrowDropDown,
                            contentDescription = "Toggle Settings",
                            modifier = Modifier.graphicsLayer(rotationZ = if (showSettings) 180f else 0f)
                        )
                    }
                    if (showSettings) {
                        Divider(modifier = Modifier.padding(vertical = dimensionResource(id = R.dimen.padding_medium)))
                        StyleSelector(
                            styleNames = styleLoader.names,
                            selectedStyles = selectedStyles,
                            onAddStyle = { style ->
                                selectedStyles = selectedStyles + style
                                weights = weights + (style to 1f)
                            },
                            onRemoveStyle = { style ->
                                selectedStyles = selectedStyles - style
                                weights = weights - style
                            }
                        )
                        WeightSliders(
                            selectedStyles = selectedStyles,
                            weights = weights,
                            onWeightChanged = { style, value ->
                                weights = weights.toMutableMap().apply { put(style, value) }
                            }
                        )
                        InterpolationModeSelector(
                            currentMode = interpolationMode,
                            onModeSelected = { interpolationMode = it }
                        )
                        Text("Speed: ${ "%.2f".format(speed)}", style = MaterialTheme.typography.bodyMedium)
                        Slider(
                            value = speed,
                            onValueChange = {
                                speed = it
                                SettingsManager.setSpeed(context, it)
                            },
                            valueRange = 0.5f..2.0f,
                            steps = 15,
                            modifier = Modifier.fillMaxWidth()
                        )
                    }
                }
            }
        }

        item {
            Card(modifier = Modifier.fillMaxWidth()) {
                Column(modifier = Modifier.padding(dimensionResource(id = R.dimen.padding_medium))) {
                    OutlinedTextField(
                        value = projectName,
                        onValueChange = { projectName = it },
                        label = { Text("Project Name") },
                        modifier = Modifier.fillMaxWidth()
                    )
                    Row(
                        verticalAlignment = Alignment.CenterVertically,
                        modifier = Modifier.padding(top = dimensionResource(id = R.dimen.padding_small))
                    ) {
                        Text("Use Pregenerated")
                        Spacer(modifier = Modifier.weight(1f))
                        Switch(checked = usePregenerated, onCheckedChange = { usePregenerated = it })
                    }
                    Row(
                        horizontalArrangement = Arrangement.spacedBy(dimensionResource(id = R.dimen.padding_small)),
                        modifier = Modifier.padding(top = dimensionResource(id = R.dimen.padding_small))
                    ) {
                        Button(onClick = {
                            bookUri?.let {
                                val project = Project(
                                    uri = it.toString(),
                                    name = projectName,
                                    styles = selectedStyles,
                                    weights = weights,
                                    mode = interpolationMode,
                                    speed = speed,
                                    bookmark = bookmark,
                                    usePregenerated = usePregenerated
                                )
                                ProjectManager.save(context, project)
                                projects = ProjectManager.list(context)
                            }
                        }) { Text("Save Project") }
                        Button(onClick = {
                            bookUri?.let {
                                ProjectManager.delete(context, it.toString())
                                projects = ProjectManager.list(context)
                                projectName = ""
                            }
                        }) { Text("Delete Project") }
                    }
                    if (projects.isNotEmpty()) {
                        Divider(modifier = Modifier.padding(top = dimensionResource(id = R.dimen.padding_small)))
                        Column(modifier = Modifier.padding(top = dimensionResource(id = R.dimen.padding_small))) {
                            projects.forEach { p ->
                                Row(
                                    verticalAlignment = Alignment.CenterVertically,
                                    modifier = Modifier.fillMaxWidth()
                                ) {
                                    Text(p.name, modifier = Modifier.weight(1f))
                                    Button(onClick = {
                                        val uri = Uri.parse(p.uri)
                                        bookViewModel.loadBook(context, uri)
                                    }) { Text("Load") }
                                    Button(onClick = {
                                        ProjectManager.delete(context, p.uri)
                                        projects = ProjectManager.list(context)
                                    }) { Text("Del") }
                                }
                            }
                        }
                    }
                }
            }
        }

        if (bookmark != null && playerState == PlayerState.IDLE) {
            item {
                Row(
                    verticalAlignment = Alignment.CenterVertically,
                    horizontalArrangement = Arrangement.spacedBy(dimensionResource(id = R.dimen.padding_medium))
                ) {
                    Text("Resume at line ${bookmark!!.line + 1}")
                    Button(onClick = { bookViewModel.setCurrentLine(bookmark!!.line) }) {
                        Text("Go")
                    }
                    Button(onClick = {
                        bookUri?.let { BookmarkManager.clear(context, it.toString()) }
                        bookmark = null
                        bookViewModel.setCurrentLine(-1)
                    }) {
                        Text("Clear")
                    }
                }
            }
        }
        item {
            FlowRow(
                modifier = Modifier.fillMaxWidth(),
                horizontalArrangement = Arrangement.spacedBy(dimensionResource(id = R.dimen.padding_small)),
                maxItemsInEachRow = 3
            ) {
                Button(onClick = { launcher.launch(arrayOf("text/plain")) }) {
                    Text("Open")
                }
                Button(
                    onClick = {
                        if (playerState == PlayerState.PLAYING) {
                            bookViewModel.audioPlayer.pause()
                            bookUri?.let {
                                val position = bookViewModel.audioPlayer.getPosition()
                                DebugLogger.log("Saving bookmark at line $currentLine, position $position")
                                BookmarkManager.save(context, it.toString(), currentLine, position)
                                val project = Project(
                                    uri = it.toString(),
                                    name = projectName,
                                    styles = selectedStyles,
                                    weights = weights,
                                    mode = interpolationMode,
                                    speed = speed,
                                    bookmark = Bookmark(currentLine, position),
                                    usePregenerated = usePregenerated
                                )
                                ProjectManager.save(context, project)
                            }
                        } else {
                            bookViewModel.startPlayback(
                                session = session,
                                phonemeConverter = phonemeConverter,
                                styleLoader = styleLoader,
                                selectedStyles = selectedStyles,
                                weights = weights,
                                mode = interpolationMode,
                                speed = speed,
                                lines = lines,
                                startLine = currentLine.coerceAtLeast(0),
                                bookUri = bookUri,
                                context = context,
                                bookmark = bookmark,
                                usePregenerated = usePregenerated,
                                onFinished = {
                                    bookUri?.let { u -> BookmarkManager.clear(context, u.toString()) }
                                    bookmark = null
                                },
                            )
                        }
                    },
                    enabled = lines.isNotEmpty()
                ) {
                    Text(
                        when (playerState) {
                            PlayerState.IDLE -> "Play"
                            PlayerState.PLAYING -> "Pause"
                            PlayerState.PAUSED -> "Resume"
                        }
                    )
                }
                Button(
                    onClick = {
                        bookViewModel.stopPlayback()
                    },
                    enabled = playerState != PlayerState.IDLE
                ) {
                    Text("Stop")
                }
                Button(
                    onClick = {
                        isProcessing = true
                        scope.launch {
                            try {
                                debugMessage = null
                                val mixedVector = mixStyles(
                                    styleLoader = styleLoader,
                                    styles = selectedStyles,
                                    weights = weights,
                                    mode = interpolationMode
                                )
                                val audioData = mutableListOf<Float>()
                                for (line in lines) {
                                    val phonemes = phonemeConverter.phonemize(line)
                                    val (audio, _) = createAudioFromStyleVector(
                                        phonemes = phonemes,
                                        voice = mixedVector,
                                        speed = speed,
                                        session = session
                                    )
                                    audioData.addAll(audio.toList())
                                }
                                val fileName = buildStyleFileName(selectedStyles, weights, interpolationMode)
                                val uri = saveAudio(audioData.toFloatArray(), context, fileName)
                                uri?.let { openAudioFile(context, it) }
                            } catch (e: Exception) {
                                debugMessage = e.localizedMessage
                            } finally {
                                isProcessing = false
                            }
                        }
                    },
                    enabled = lines.isNotEmpty() && !isProcessing
                ) {
                    Text(if (isProcessing) "Saving..." else "Save")
                }
                if (selectedLines.isNotEmpty()) {
                    Button(
                        onClick = {
                            isProcessing = true
                            scope.launch {
                                try {
                                    debugMessage = null
                                    val mixedVector = mixStyles(
                                        styleLoader = styleLoader,
                                        styles = selectedStyles,
                                        weights = weights,
                                        mode = interpolationMode
                                    )
                                    val audioData = mutableListOf<Float>()
                                    for (i in selectedLines.sorted()) {
                                        val phonemes = phonemeConverter.phonemize(lines[i])
                                        val (audio, _) = createAudioFromStyleVector(
                                            phonemes = phonemes,
                                            voice = mixedVector,
                                            speed = speed,
                                            session = session
                                        )
                                        audioData.addAll(audio.toList())
                                    }
                                    val fileName = buildStyleFileName(selectedStyles, weights, interpolationMode) + "_clip"
                                    val uri = saveAudio(audioData.toFloatArray(), context, fileName)
                                    uri?.let { openAudioFile(context, it) }
                                    selectedLines.clear()
                                } catch (e: Exception) {
                                    debugMessage = e.localizedMessage
                                } finally {
                                    isProcessing = false
                                }
                            }
                        },
                        enabled = !isProcessing
                    ) {
                        Text(if (isProcessing) "Saving..." else "Save Clip")
                    }
                }
                Button(
                    onClick = {
                        if (bookUri != null) {
                            isPregenerating = true
                            preGenProgress = 0f
                            scope.launch {
                                try {
                                    val project = Project(
                                        uri = bookUri!!.toString(),
                                        name = projectName,
                                        styles = selectedStyles,
                                        weights = weights,
                                        mode = interpolationMode,
                                        speed = speed,
                                        bookmark = bookmark,
                                        usePregenerated = true
                                    )
                                    preGenerateBook(
                                        context = context,
                                        session = session,
                                        phonemeConverter = phonemeConverter,
                                        styleLoader = styleLoader,
                                        project = project,
                                        lines = lines,
                                        onProgress = { preGenProgress = it }
                                    )
                                    usePregenerated = true
                                    projects = ProjectManager.list(context)
                                } catch (e: Exception) {
                                    debugMessage = e.localizedMessage
                                } finally {
                                    isPregenerating = false
                                }
                            }
                        }
                    },
                    enabled = !isPregenerating && lines.isNotEmpty() && bookUri != null
                ) {
                    Text(if (isPregenerating) "Pre-generating..." else "Pregenerate")
                }
            }
        }

        itemsIndexed(lines) { index, line ->
            Text(
                text = line,
                modifier = Modifier
                    .fillMaxWidth()
                    .combinedClickable(
                        onClick = {
                            bookViewModel.setCurrentLine(index)
                            bookViewModel.startPlayback(
                                session = session,
                                phonemeConverter = phonemeConverter,
                                styleLoader = styleLoader,
                                selectedStyles = selectedStyles,
                                weights = weights,
                                mode = interpolationMode,
                                speed = speed,
                                lines = lines,
                                startLine = index,
                                bookUri = bookUri,
                                context = context,
                                bookmark = bookmark,
                                usePregenerated = usePregenerated,
                                onFinished = {
                                    bookUri?.let { u -> BookmarkManager.clear(context, u.toString()) }
                                    bookmark = null
                                },
                            )
                        },
                        onLongClick = {
                            if (selectedLines.contains(index)) {
                                selectedLines.remove(index)
                            } else {
                                selectedLines.add(index)
                            }
                        }
                    )
                    .background(
                        when {
                            selectedLines.contains(index) -> MaterialTheme.colorScheme.secondaryContainer
                            index == currentLine -> MaterialTheme.colorScheme.primaryContainer
                            else -> Color.Transparent
                        }
                    )
                    .padding(dimensionResource(id = R.dimen.padding_small)),
                textAlign = TextAlign.Justify,
                style = MaterialTheme.typography.bodyLarge
            )
        }

        item {
            debugMessage?.let {
                Text(
                    text = it,
                    color = MaterialTheme.colorScheme.error,
                    modifier = Modifier.padding(top = dimensionResource(id = R.dimen.padding_medium))
                )
            }
        }

        item {
            if (SettingsManager.isDebug(context)) {
                val logs = DebugLogger.getLogs().joinToString("\n")
                Text(logs, modifier = Modifier.padding(top = dimensionResource(id = R.dimen.padding_medium)))
            }
        }
    }

    if (isPregenerating) {
        ProgressDialog(
            message = "Pre-generating ${(preGenProgress * 100).toInt()}%",
            progress = preGenProgress
        )
    }
}


