package com.mewmix.nabu.screens

import android.Manifest
import android.content.Context
import android.content.Intent
import android.content.pm.PackageManager
import android.net.Uri
import android.provider.OpenableColumns
import android.os.Build
import androidx.activity.compose.rememberLauncherForActivityResult
import androidx.activity.result.contract.ActivityResultContracts
import androidx.compose.foundation.ExperimentalFoundationApi
import androidx.compose.foundation.background
import androidx.compose.foundation.clickable
import androidx.compose.foundation.combinedClickable
import androidx.compose.foundation.layout.*
import androidx.compose.foundation.layout.PaddingValues
import androidx.compose.foundation.lazy.LazyColumn
import androidx.compose.foundation.lazy.LazyListState
import androidx.compose.foundation.lazy.itemsIndexed
import androidx.compose.foundation.lazy.rememberLazyListState
import androidx.compose.foundation.shape.RoundedCornerShape
import androidx.compose.material3.*
import androidx.compose.runtime.*
import androidx.compose.ui.Alignment
import androidx.compose.ui.Modifier
import androidx.compose.ui.graphics.Color
import androidx.compose.ui.graphics.Brush
import androidx.compose.ui.graphics.RectangleShape
import androidx.compose.ui.graphics.Shape
import androidx.compose.ui.platform.LocalContext
import androidx.compose.ui.res.dimensionResource
import androidx.compose.ui.text.style.TextAlign
import androidx.compose.ui.text.TextStyle
import androidx.lifecycle.viewmodel.compose.viewModel
import androidx.core.content.ContextCompat
import com.mewmix.nabu.R
import com.mewmix.nabu.utils.*
import com.mewmix.nabu.ui.components.ProgressDialog
import com.mewmix.nabu.ui.components.RadialWaveformVisualizer
import com.mewmix.nabu.ui.components.WaveformVisualizer
import com.mewmix.nabu.ui.components.RuntimeStatusLine
import com.mewmix.nabu.viewmodel.BookViewModel
import com.mewmix.nabu.tts.TTSManager
import com.mewmix.nabu.data.ModelManager
import com.mewmix.nabu.kokoro.KokoroEngine
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.launch
import kotlinx.coroutines.withContext
import com.mewmix.nabu.ui.brutalist.PanelBox
import com.mewmix.nabu.ui.brutalist.BrutalSection
import com.mewmix.nabu.ui.brutalist.Brutal
import com.mewmix.nabu.ui.brutalist.BrutalButton
import com.mewmix.nabu.ui.brutalist.BrutalSlider
import com.mewmix.nabu.ui.brutalist.SwitchToggle
import androidx.compose.ui.unit.dp
import com.mewmix.nabu.ChatActivity
import java.util.Locale

@OptIn(ExperimentalMaterial3Api::class, ExperimentalLayoutApi::class, ExperimentalFoundationApi::class)
@Composable
fun BookScreen(
    phonemeConverter: PhonemeConverter,
    bookViewModel: BookViewModel = viewModel()
) {
    val context = LocalContext.current
    val scope = rememberCoroutineScope()
    val notificationPermissionLauncher = rememberLauncherForActivityResult(
        contract = ActivityResultContracts.RequestPermission()
    ) { }

    LaunchedEffect(Unit) {
        withContext(Dispatchers.IO) {
            OnnxRuntimeManager.initialize(context.applicationContext)
        }
    }

    val playableUnits by bookViewModel.playableUnits.collectAsState()
    val currentUnitIndex by bookViewModel.currentUnitIndex.collectAsState()
    val lines = playableUnits.map { it.text }
    val playerState by bookViewModel.playerState.collectAsState()

    val bookUri by bookViewModel.bookUri.collectAsState()
    val bookDisplayName by bookViewModel.bookDisplayName.collectAsState()
    var bookmark by remember { mutableStateOf<Bookmark?>(null) }

    val listState = rememberLazyListState()

    val styleLoader = remember { StyleLoader(context) }
    val defaultVoice = styleLoader.names.firstOrNull() ?: "af_sky"
    var selectedStyles by remember { mutableStateOf(listOf(defaultVoice)) }
    var weights by remember { mutableStateOf(mapOf(defaultVoice to 1f)) }
    var interpolationMode by remember { mutableStateOf(InterpolationMode.LINEAR) }
    var speed by remember { mutableFloatStateOf(SettingsManager.getSpeed(context)) }
    var debugMessage by remember { mutableStateOf<String?>(null) }
    var isProcessing by remember { mutableStateOf(false) }
    var isPregenerating by remember { mutableStateOf(false) }
    var preGenProgress by remember { mutableFloatStateOf(0f) }
    var isPreparing by remember { mutableStateOf(false) }

    var showSettings by remember { mutableStateOf(false) }
    var showProjectSection by remember { mutableStateOf(false) }

    var projectName by remember { mutableStateOf("") }
    var usePregenerated by remember { mutableStateOf(false) }
    var projects by remember { mutableStateOf(listOf<Project>()) }
    val selectedLines = remember { mutableStateListOf<Int>() }
    var followText by remember { mutableStateOf(true) }
    var showEditorSection by remember { mutableStateOf(false) }
    var isEditMode by remember { mutableStateOf(false) }
    var editingLineIndex by remember { mutableStateOf<Int?>(null) }
    var editorText by remember { mutableStateOf("") }
    var editedFileName by remember { mutableStateOf("edited_book.epub") }
    var isSavingEdited by remember { mutableStateOf(false) }
    var saveMessage by remember { mutableStateOf<String?>(null) }
    var saveSuccessful by remember { mutableStateOf(false) }
    var pendingSaveDisplayName by remember { mutableStateOf<String?>(null) }
    var isImmersiveReader by remember { mutableStateOf(false) }

    fun buildSaveFileName(isKokoro: Boolean, suffix: String = ""): String {
        val baseName = if (isKokoro) {
            buildStyleFileName(selectedStyles, weights, interpolationMode)
        } else {
            val styleLabel = selectedStyles.joinToString("-").ifBlank { "supertonic" }
            "supertonic_$styleLabel"
        }
        return baseName + suffix
    }

    fun buildEditedDisplayName(name: String): String {
        val currentBookDisplayName = bookDisplayName
        val trimmed = name.trim().ifBlank {
            currentBookDisplayName
                ?.substringBeforeLast('.', currentBookDisplayName)
                ?.takeIf { it.isNotBlank() }
                ?.let { "${it}_edited" }
                ?: "edited_book"
        }
        return if (trimmed.lowercase(Locale.US).endsWith(".epub")) trimmed else "$trimmed.epub"
    }

    val saveEditedDocumentLauncher = rememberLauncherForActivityResult(
        contract = ActivityResultContracts.CreateDocument(EpubWriter.MIME_TYPE)
    ) { uri: Uri? ->
        val displayName = pendingSaveDisplayName
        pendingSaveDisplayName = null
        if (uri == null || displayName == null) {
            if (uri == null && isSavingEdited) {
                saveMessage = "Save canceled"
                saveSuccessful = false
            }
            isSavingEdited = false
            return@rememberLauncherForActivityResult
        }
        scope.launch {
            try {
                val saved = bookViewModel.saveEditedCopy(context, uri, displayName)
                if (saved) {
                    saveMessage = "Saved edited copy"
                    saveSuccessful = true
                } else {
                    saveMessage = "Unable to save edited copy"
                    saveSuccessful = false
                }
            } catch (e: Exception) {
                saveMessage = e.localizedMessage ?: "Failed to save edited copy"
                saveSuccessful = false
            } finally {
                isSavingEdited = false
            }
        }
    }

    val launcher = rememberLauncherForActivityResult(
        contract = ActivityResultContracts.OpenDocument()
    ) { uri: Uri? ->
        uri?.let {
            // Persist read permission so the URI can be reopened later from saved projects
            context.contentResolver.takePersistableUriPermission(
                it,
                Intent.FLAG_GRANT_READ_URI_PERMISSION
            )
            bookViewModel.openDocument(it)
            bookViewModel.loadBook(context, it)
        }
    }

    LaunchedEffect(Unit) {
        projects = ProjectManager.list(context)
        if (bookUri == null) {
            val lastUri = SettingsManager.getLastBookUri(context)
            if (!lastUri.isNullOrBlank()) {
                runCatching {
                    bookViewModel.loadBook(context, Uri.parse(lastUri))
                }.onFailure {
                    DebugLogger.log("BookScreen: failed to load last book: ${it.localizedMessage}")
                }
            }
        }
    }

    LaunchedEffect(bookUri) {
        bookUri?.let { uri ->
            val project = ProjectManager.load(context, uri.toString())
            if (project != null) {
                selectedStyles = project.styles.ifEmpty { listOf(defaultVoice) }
                weights = if (project.weights.isNotEmpty()) project.weights else mapOf(defaultVoice to 1f)
                interpolationMode = project.mode
                speed = project.speed
                bookmark = project.bookmark
                 projectName = project.name
                 usePregenerated = project.usePregenerated
                DebugLogger.log("Loaded project: $project")
                bookViewModel.setCurrentUnitIndex(project.bookmark?.line ?: 0)
            } else {
                bookmark = BookmarkManager.load(context, uri.toString())
                DebugLogger.log("Loaded bookmark: $bookmark")
                bookmark?.let { bookViewModel.setCurrentUnitIndex(it.line) } ?: bookViewModel.setCurrentUnitIndex(0)
            }
            projects = ProjectManager.list(context)
        }
        editingLineIndex = null
        editorText = ""
        isEditMode = false
        saveMessage = null
        isSavingEdited = false
        saveSuccessful = false
        pendingSaveDisplayName = null
    }

    LaunchedEffect(currentUnitIndex, followText) {
        if (followText && currentUnitIndex >= 0) {
            listState.animateScrollToItem(currentUnitIndex)
        }
    }

    LaunchedEffect(bookDisplayName) {
        val currentBookDisplayName = bookDisplayName
        val suggestion = currentBookDisplayName
            ?.substringBeforeLast('.', currentBookDisplayName)
            ?.takeIf { it.isNotBlank() }
            ?.let { "${it}_edited.epub" }
            ?: "edited_book.epub"
        editedFileName = suggestion
    }

    LaunchedEffect(editingLineIndex, lines) {
        editingLineIndex?.let { index ->
            editorText = lines.getOrNull(index) ?: ""
        }
    }

    LaunchedEffect(playerState) {
        PcmTap.enabled = playerState == PlayerState.PLAYING
        if (playerState != PlayerState.IDLE) {
            isPreparing = false
        }
    }

    LaunchedEffect(lines) {
        if (lines.isEmpty()) {
            isImmersiveReader = false
        }
    }

    fun startPlaybackFromLine(index: Int) {
        maybeRequestNotificationPermission(context, notificationPermissionLauncher)
        bookViewModel.setCurrentUnitIndex(index)
        bookViewModel.startPlayback(
            phonemeConverter = phonemeConverter,
            styleLoader = styleLoader,
            selectedStyles = selectedStyles,
            weights = weights,
            mode = interpolationMode,
            speed = speed,
            units = playableUnits,
            startUnit = index,
            bookUri = bookUri,
            projectName = projectName,
            context = context,
            usePregenerated = usePregenerated,
            onFinished = {
                bookUri?.let { u -> BookmarkManager.clear(context, u.toString()) }
                bookmark = null
            },
        )
    }

    fun handleLineClick(index: Int) {
        if (isEditMode) {
            editingLineIndex = index
        } else if (selectedLines.contains(index)) {
            selectedLines.remove(index)
        } else {
            startPlaybackFromLine(index)
        }
    }

    fun handleLineLongPress(index: Int) {
        if (selectedLines.contains(index)) {
            selectedLines.remove(index)
        } else {
            selectedLines.add(index)
        }
    }

    fun handleLineDoubleTap(index: Int) {
        bookmark = Bookmark(index)
        bookUri?.let { BookmarkManager.save(context, it.toString(), index) }
    }

    if (!isImmersiveReader) {
        PanelBox(
            modifier = Modifier
                .fillMaxSize()
                .padding(dimensionResource(id = R.dimen.padding_large))
        ) {
            val defaultLineVisuals = defaultReaderLineVisuals()
            LazyColumn(
            modifier = Modifier.fillMaxSize(),
            verticalArrangement = Arrangement.spacedBy(dimensionResource(id = R.dimen.padding_medium)),
            state = listState
        ) {
        item {
            RuntimeStatusLine(
                modifier = Modifier
                    .fillMaxWidth()
                    .padding(bottom = 4.dp)
            )
        }
        item {
            BrutalSection(
                title = "Settings",
                expanded = showSettings,
                onToggle = { showSettings = !showSettings }
            ) {
                StyleSelector(
                    styleNames = styleLoader.names,
                    selectedStyles = selectedStyles,
                    onAddStyle = { style ->
                        selectedStyles = selectedStyles + style
                        weights = weights + (style to 1f)
                    },
                    onRemoveStyle = { style ->
                        selectedStyles = selectedStyles - style
                        weights = weights - style
                    }
                )
                WeightSliders(
                    selectedStyles = selectedStyles,
                    weights = weights,
                    onWeightChanged = { style, value ->
                        weights = weights.toMutableMap().apply { put(style, value) }
                    }
                )
                InterpolationModeSelector(
                    currentMode = interpolationMode,
                    onModeSelected = { interpolationMode = it }
                )
                Text(
                    "Speed: ${ "%.2f".format(speed)}",
                    style = MaterialTheme.typography.bodyMedium,
                    color = MaterialTheme.colorScheme.onSurface
                )
                BrutalSlider(
                    value = speed,
                    onValueChange = { newSpeed ->
                        speed = newSpeed
                        SettingsManager.setSpeed(context, newSpeed)
                    },
                    range = 0.5f..2.0f,
                    modifier = Modifier.fillMaxWidth()
                )
            }
        }

        item {
            BrutalSection(
                title = "Projects",
                expanded = showProjectSection,
                onToggle = { showProjectSection = !showProjectSection }
            ) {
                OutlinedTextField(
                    value = projectName,
                    onValueChange = { projectName = it },
                    label = { Text("Project Name") },
                    modifier = Modifier.fillMaxWidth()
                )
                Row(
                    verticalAlignment = Alignment.CenterVertically,
                    modifier = Modifier.padding(top = dimensionResource(id = R.dimen.padding_small))
                ) {
                    Text("Use Pregenerated", color = MaterialTheme.colorScheme.onSurface)
                    Spacer(modifier = Modifier.weight(1f))
                    Switch(checked = usePregenerated, onCheckedChange = { usePregenerated = it })
                }
                Row(
                    horizontalArrangement = Arrangement.spacedBy(dimensionResource(id = R.dimen.padding_small)),
                    modifier = Modifier.padding(top = dimensionResource(id = R.dimen.padding_small))
                ) {
                    BrutalButton(onClick = {
                        bookUri?.let {
                            val project = Project(
                                uri = it.toString(),
                                name = projectName,
                                styles = selectedStyles,
                                weights = weights,
                                mode = interpolationMode,
                                speed = speed,
                                bookmark = bookmark,
                                usePregenerated = usePregenerated
                            )
                            ProjectManager.save(context, project)
                            projects = ProjectManager.list(context)
                        }
                    }) { Text("Save Project") }
                    BrutalButton(onClick = {
                        bookUri?.let {
                            ProjectManager.delete(context, it.toString())
                            projects = ProjectManager.list(context)
                            projectName = ""
                        }
                    }) { Text("Delete Project") }
                }
                if (projects.isNotEmpty()) {
                    Divider(modifier = Modifier.padding(top = dimensionResource(id = R.dimen.padding_small)))
                    Column(modifier = Modifier.padding(top = dimensionResource(id = R.dimen.padding_small))) {
                        projects.forEach { p ->
                            Row(
                                verticalAlignment = Alignment.CenterVertically,
                                modifier = Modifier.fillMaxWidth()
                            ) {
                                Text(p.name, modifier = Modifier.weight(1f), color = MaterialTheme.colorScheme.onSurface)
                                BrutalButton(onClick = {
                                    val uri = Uri.parse(p.uri)
                                    bookViewModel.openDocument(uri)
                                    bookViewModel.loadBook(context, uri)
                                }) { Text("Load") }
                                BrutalButton(onClick = {
                                    ProjectManager.delete(context, p.uri)
                                    projects = ProjectManager.list(context)
                                }) { Text("Del") }
                            }
                        }
                    }
                }
            }
        }

        item {
            BrutalSection(
                title = "Editor",
                expanded = showEditorSection,
                onToggle = { showEditorSection = !showEditorSection }
            ) {
                SwitchToggle(
                    checked = isEditMode,
                    onToggle = {
                        isEditMode = it
                        if (!it) {
                            editingLineIndex = null
                            editorText = ""
                        }
                    },
                    label = "Editing Mode"
                )
                if (isEditMode) {
                    Text(
                        text = if (editingLineIndex != null) {
                            "Editing line ${editingLineIndex!! + 1}"
                        } else {
                            "Tap a line below to load it into the editor"
                        },
                        color = MaterialTheme.colorScheme.onSurface,
                        modifier = Modifier.padding(top = dimensionResource(id = R.dimen.padding_small))
                    )
                    if (editingLineIndex != null) {
                        OutlinedTextField(
                            value = editorText,
                            onValueChange = { editorText = it },
                            modifier = Modifier
                                .fillMaxWidth()
                                .heightIn(min = 160.dp)
                                .padding(top = dimensionResource(id = R.dimen.padding_small)),
                            label = { Text("Line Text") },
                            supportingText = { Text("Changes apply only when you tap Apply Change") }
                        )
                        Row(
                            horizontalArrangement = Arrangement.spacedBy(dimensionResource(id = R.dimen.padding_small)),
                            modifier = Modifier.padding(top = dimensionResource(id = R.dimen.padding_small))
                        ) {
                            BrutalButton(onClick = {
                                editingLineIndex?.let { index ->
                                    bookViewModel.updatePlayableUnitText(index, editorText)
                                    saveMessage = "Updated line ${index + 1}"
                                    saveSuccessful = true
                                }
                            }) { Text("Apply Change") }
                            BrutalButton(onClick = {
                                editingLineIndex?.let { index ->
                                    editorText = lines.getOrNull(index) ?: ""
                                }
                            }) { Text("Reset") }
                        }
                    }
                }
                OutlinedTextField(
                    value = editedFileName,
                    onValueChange = { editedFileName = it },
                    label = { Text("Edited File Name") },
                    modifier = Modifier
                        .fillMaxWidth()
                        .padding(top = dimensionResource(id = R.dimen.padding_small))
                )
                BrutalButton(
                    onClick = {
                        if (isSavingEdited || lines.isEmpty()) {
                            return@BrutalButton
                        }
                        val displayName = buildEditedDisplayName(editedFileName)
                        editedFileName = displayName
                        isSavingEdited = true
                        saveMessage = null
                        saveSuccessful = false
                        pendingSaveDisplayName = displayName
                        saveEditedDocumentLauncher.launch(displayName)
                    },
                    enabled = !isSavingEdited && lines.isNotEmpty(),
                    modifier = Modifier.padding(top = dimensionResource(id = R.dimen.padding_small))
                ) {
                    Text(if (isSavingEdited) "SAVING..." else "SAVE EDITED COPY")
                }
                saveMessage?.let { message ->
                    Text(
                        text = message,
                        color = if (saveSuccessful) MaterialTheme.colorScheme.onSurface else MaterialTheme.colorScheme.error,
                        modifier = Modifier.padding(top = dimensionResource(id = R.dimen.padding_small))
                    )
                }
            }
        }

        if (bookmark != null && playerState == PlayerState.IDLE) {
            item {
                Row(
                    verticalAlignment = Alignment.CenterVertically,
                    horizontalArrangement = Arrangement.spacedBy(dimensionResource(id = R.dimen.padding_medium))
                ) {
                    Text("Resume at line ${bookmark!!.line + 1}")
                    BrutalButton(onClick = { bookViewModel.setCurrentUnitIndex(bookmark!!.line) }) {
                        Text("Go")
                    }
                    BrutalButton(onClick = {
                        bookUri?.let { BookmarkManager.clear(context, it.toString()) }
                        bookmark = null
                        bookViewModel.setCurrentUnitIndex(-1)
                    }) {
                        Text("Clear")
                    }
                }
            }
        }
        item {
            FlowRow(
                modifier = Modifier.fillMaxWidth(),
                horizontalArrangement = Arrangement.Center,
                maxItemsInEachRow = 3
            ) {
                BrutalButton(onClick = { launcher.launch(arrayOf("text/plain", "application/epub+zip")) }) {
                    Text("OPEN")
                }
                BrutalButton(
                    onClick = { isImmersiveReader = true },
                    enabled = lines.isNotEmpty()
                ) {
                    Text("FOCUS")
                }
                val startPlaybackAction = {
                    maybeRequestNotificationPermission(context, notificationPermissionLauncher)
                    if (playerState == PlayerState.PAUSED) {
                        bookViewModel.audioPlayer.stop()
                    }
                    isPreparing = true
                    bookViewModel.startPlayback(
                        phonemeConverter = phonemeConverter,
                        styleLoader = styleLoader,
                        selectedStyles = selectedStyles,
                        weights = weights,
                        mode = interpolationMode,
                        speed = speed,
                        units = playableUnits,
                        startUnit = currentUnitIndex.coerceAtLeast(0),
                        bookUri = bookUri,
                        projectName = projectName,
                        context = context,
                        usePregenerated = usePregenerated,
                        onFinished = {
                            bookUri?.let { u -> BookmarkManager.clear(context, u.toString()) }
                            bookmark = null
                        },
                    )
                }
                when (playerState) {
                    PlayerState.IDLE -> {
                        BrutalButton(
                            onClick = { startPlaybackAction() },
                            enabled = lines.isNotEmpty() && !isPreparing
                        ) {
                            Text(if (isPreparing) "GPU PROCESSING..." else "PLAY")
                        }
                    }
                    PlayerState.PLAYING -> {
                        BrutalButton(onClick = {
                            bookViewModel.audioPlayer.pause()
                            bookUri?.let {
                                DebugLogger.log("Saving bookmark at line $currentUnitIndex")
                                BookmarkManager.save(context, it.toString(), currentUnitIndex)
                                val project = Project(
                                    uri = it.toString(),
                                    name = projectName,
                                    styles = selectedStyles,
                                    weights = weights,
                                    mode = interpolationMode,
                                    speed = speed,
                                    bookmark = Bookmark(currentUnitIndex),
                                    usePregenerated = usePregenerated
                                )
                                ProjectManager.save(context, project)
                                bookmark = Bookmark(currentUnitIndex)
                            }
                        }) {
                            Text("PAUSE")
                        }
                        BrutalButton(onClick = { bookViewModel.stopPlayback() }) {
                            Text("STOP")
                        }
                    }
                    PlayerState.PAUSED -> {
                        BrutalButton(
                            onClick = { startPlaybackAction() },
                            enabled = lines.isNotEmpty() && !isPreparing
                        ) {
                            Text(if (isPreparing) "GPU PROCESSING..." else "PLAY")
                        }
                        BrutalButton(onClick = { bookViewModel.stopPlayback() }) {
                            Text("STOP")
                        }
                    }
                }
                BrutalButton(
                    onClick = {
                        isProcessing = true
                        scope.launch {
                            try {
                                debugMessage = null
                                val (audioData, sampleRate, isKokoro) = withContext(Dispatchers.IO) {
                                    val modelManager = ModelManager(context)
                                    val engineInstance = TTSManager.getEngine(context, modelManager)
                                        ?: throw IllegalStateException("TTS engine not ready")
                                    
                                    val collected = mutableListOf<Float>()
                                    val rawEngine = if (engineInstance is com.mewmix.nabu.tts.BenchmarkingTTSEngine) engineInstance.delegate else engineInstance

                                    val kokoroVector = if (rawEngine is KokoroEngine) {
                                        mixStyles(
                                            styleLoader = styleLoader,
                                            styles = selectedStyles,
                                            weights = weights,
                                            mode = interpolationMode
                                        )
                                    } else {
                                        null
                                    }

                                    if (rawEngine is KokoroEngine && kokoroVector != null) {
                                        for (line in lines) {
                                            val phonemes = phonemeConverter.phonemize(line)
                                            val (audio, _) = createAudioFromStyleVector(
                                                phonemes = phonemes,
                                                voice = kokoroVector,
                                                speed = speed,
                                                engine = rawEngine
                                            )
                                            collected.addAll(audio.toList())
                                        }
                                    } else {
                                        // Generic TTSEngine (Supertonic)
                                        if (rawEngine is com.mewmix.nabu.supertonic.DebugSupertonicEngine && selectedStyles.isNotEmpty()) {
                                            rawEngine.setStyle(selectedStyles.first())
                                        }
                                        for (line in lines) {
                                            val result = engineInstance.synthesize(line, speed)
                                            collected.addAll(result.wav.toList())
                                        }
                                    }
                                    Triple(collected.toFloatArray(), engineInstance.sampleRate, rawEngine is KokoroEngine)
                                }
                                val fileName = buildSaveFileName(isKokoro = isKokoro)
                                val uri = saveAudio(audioData, context, fileName, sampleRate)
                                uri?.let { openAudioFile(context, it) }
                            } catch (e: Exception) {
                                debugMessage = e.localizedMessage
                            } finally {
                                isProcessing = false
                            }
                        }
                    },
                    enabled = lines.isNotEmpty() && !isProcessing
                ) {
                    Text(if (isProcessing) "SAVING..." else "SAVE")
                }
                if (selectedLines.isNotEmpty()) {
                    BrutalButton(
                        onClick = {
                            isProcessing = true
                            scope.launch {
                                try {
                                    debugMessage = null
                                    val (audioData, sampleRate, isKokoro) = withContext(Dispatchers.IO) {
                                    val modelManager = ModelManager(context)
                                    val engineInstance = TTSManager.getEngine(context, modelManager)
                                        ?: throw IllegalStateException("TTS engine not ready")
                                    
                                    val collected = mutableListOf<Float>()
                                    val rawEngine = if (engineInstance is com.mewmix.nabu.tts.BenchmarkingTTSEngine) engineInstance.delegate else engineInstance

                                    val kokoroVector = if (rawEngine is KokoroEngine) {
                                        mixStyles(
                                            styleLoader = styleLoader,
                                            styles = selectedStyles,
                                            weights = weights,
                                            mode = interpolationMode
                                        )
                                    } else {
                                        null
                                    }

                                    if (rawEngine is KokoroEngine && kokoroVector != null) {
                                        for (i in selectedLines.sorted()) {
                                            val phonemes = phonemeConverter.phonemize(lines[i])
                                            val (audio, _) = createAudioFromStyleVector(
                                                phonemes = phonemes,
                                                voice = kokoroVector,
                                                speed = speed,
                                                engine = rawEngine
                                            )
                                            collected.addAll(audio.toList())
                                        }
                                    } else {
                                        // Generic TTSEngine (Supertonic)
                                        if (rawEngine is com.mewmix.nabu.supertonic.DebugSupertonicEngine && selectedStyles.isNotEmpty()) {
                                            rawEngine.setStyle(selectedStyles.first())
                                        }
                                        for (i in selectedLines.sorted()) {
                                            val result = engineInstance.synthesize(lines[i], speed)
                                            collected.addAll(result.wav.toList())
                                        }
                                    }
                                    Triple(collected.toFloatArray(), engineInstance.sampleRate, rawEngine is KokoroEngine)
                                }
                                val fileName = buildSaveFileName(isKokoro = isKokoro, suffix = "_clip")
                                val uri = saveAudio(audioData, context, fileName, sampleRate)
                                uri?.let { openAudioFile(context, it) }
                                selectedLines.clear()
                            } catch (e: Exception) {
                                debugMessage = e.localizedMessage
                            } finally {
                                isProcessing = false
                            }
                        }
                    },
                    enabled = !isProcessing
                ) {
                        Text(if (isProcessing) "SAVING..." else "SAVE CLIP")
                    }
                    BrutalButton(
                        onClick = {
                            val selectedText = selectedLines.sorted().joinToString("\n") { lines[it] }
                            val title = bookUri?.let { getDisplayName(context, it).substringBeforeLast('.') } ?: "unknown"
                            val prompt = "Tell me a little bit more about this passage from: $title\n\n$selectedText"
                            val intent = Intent(context, ChatActivity::class.java).apply {
                                putExtra(ChatActivity.EXTRA_INITIAL_PROMPT, prompt)
                            }
                            context.startActivity(intent)
                            selectedLines.clear()
                        },
                        enabled = !isProcessing
                    ) {
                        Text("CHAT")
                    }
                }
                BrutalButton(
                    onClick = {
                        if (bookUri != null) {
                            isPregenerating = true
                            preGenProgress = 0f
                            scope.launch {
                                try {
                                    val project = Project(
                                        uri = bookUri!!.toString(),
                                        name = projectName,
                                        styles = selectedStyles,
                                        weights = weights,
                                        mode = interpolationMode,
                                        speed = speed,
                                        bookmark = bookmark,
                                        usePregenerated = true
                                    )
                                    preGenerateBook(
                                        context = context,
                                        phonemeConverter = phonemeConverter,
                                        styleLoader = styleLoader,
                                        project = project,
                                        lines = lines,
                                        onProgress = { preGenProgress = it }
                                    )
                                    usePregenerated = true
                                    projects = ProjectManager.list(context)
                                } catch (e: Exception) {
                                    debugMessage = e.localizedMessage
                                } finally {
                                    isPregenerating = false
                                }
                            }
                        }
                    },
                    enabled = !isPregenerating && lines.isNotEmpty() && bookUri != null
                ) {
                    Text(if (isPregenerating) "PRE-GENERATING..." else "PREGENERATE")
                }
            }
        }

        item {
            SwitchToggle(
                checked = followText,
                onToggle = { followText = it },
                label = "Follow Text"
            )
        }

        item {
            RadialWaveformVisualizer(
                modifier = Modifier
                    .fillMaxWidth()
                    .height(150.dp),
                visible = playerState == PlayerState.PLAYING
            )
        }

        itemsIndexed(lines) { index, line ->
            Text(
                text = line,
                modifier = Modifier
                    .fillMaxWidth()
                    .combinedClickable(
                        onClick = {
                            if (selectedLines.contains(index)) {
                                selectedLines.remove(index)
                            } else {
                                bookViewModel.setCurrentUnitIndex(index)
                                maybeRequestNotificationPermission(context, notificationPermissionLauncher)
                                bookViewModel.startPlayback(
                                    phonemeConverter = phonemeConverter,
                                    styleLoader = styleLoader,
                                    selectedStyles = selectedStyles,
                                    weights = weights,
                                    mode = interpolationMode,
                                    speed = speed,
                                    units = playableUnits,
                                    startUnit = index,
                                    bookUri = bookUri,
                                    projectName = projectName,
                                    context = context,
                                    usePregenerated = usePregenerated,
                                    onFinished = {
                                        bookUri?.let { u -> BookmarkManager.clear(context, u.toString()) }
                                        bookmark = null
                                    },
                                )
                            }
                        },
                        onLongClick = {
                            if (selectedLines.contains(index)) {
                                selectedLines.remove(index)
                            } else {
                                selectedLines.add(index)
                            }
                        }
                    )
                    .background(
                        when {
                            selectedLines.contains(index) -> MaterialTheme.colorScheme.secondaryContainer
                            index == currentUnitIndex -> MaterialTheme.colorScheme.primaryContainer
                            else -> Color.Transparent
                        }
                    )
                    .padding(dimensionResource(id = R.dimen.padding_small)),
                color = when {
                    selectedLines.contains(index) -> MaterialTheme.colorScheme.onSecondaryContainer
                    index == currentUnitIndex -> MaterialTheme.colorScheme.onPrimaryContainer
                    else -> MaterialTheme.colorScheme.onSurface
                },
                textAlign = TextAlign.Justify,
                style = MaterialTheme.typography.bodyLarge
            )
        }

        item {
            debugMessage?.let {
                Text(
                    text = it,
                    color = MaterialTheme.colorScheme.error,
                    modifier = Modifier.padding(top = dimensionResource(id = R.dimen.padding_medium))
                )
            }
        }

        // Debug logs moved to dedicated screen
    }
    }

    }

    if (isImmersiveReader) {
        ImmersiveReaderOverlay(
            lines = lines,
            listState = listState,
            currentUnitIndex = currentUnitIndex,
            selectedLines = selectedLines,
            playerState = playerState,
            onDismiss = { isImmersiveReader = false },
            onLineClick = ::handleLineClick,
            onLineLongPress = ::handleLineLongPress,
            onLineDoubleTap = ::handleLineDoubleTap
        )
    }

    if (isPregenerating) {
        ProgressDialog(
            message = "Pre-generating ${(preGenProgress * 100).toInt()}%",
            progress = preGenProgress
        )
    }
}

private fun maybeRequestNotificationPermission(
    context: Context,
    launcher: androidx.activity.result.ActivityResultLauncher<String>
) {
    if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.TIRAMISU &&
        ContextCompat.checkSelfPermission(
            context,
            Manifest.permission.POST_NOTIFICATIONS
        ) != PackageManager.PERMISSION_GRANTED
    ) {
        launcher.launch(Manifest.permission.POST_NOTIFICATIONS)
    }
}

@Composable
private fun ImmersiveReaderOverlay(
    lines: List<String>,
    listState: LazyListState,
    currentUnitIndex: Int,
    selectedLines: List<Int>,
    playerState: PlayerState,
    onDismiss: () -> Unit,
    onLineClick: (Int) -> Unit,
    onLineLongPress: (Int) -> Unit,
    onLineDoubleTap: (Int) -> Unit,
) {
    val visuals = immersiveReaderLineVisuals()
    Box(
        modifier = Modifier
            .fillMaxSize()
            .background(MaterialTheme.colorScheme.surface.copy(alpha = 0.96f))
    ) {
        RadialWaveformVisualizer(
            modifier = Modifier
                .fillMaxSize()
                .padding(48.dp),
            lineColor = MaterialTheme.colorScheme.primary.copy(alpha = 0.4f),
            visible = playerState != PlayerState.IDLE
        )
        Box(
            modifier = Modifier
                .fillMaxSize()
                .background(
                    Brush.verticalGradient(
                        listOf(
                            MaterialTheme.colorScheme.surface.copy(alpha = 0.94f),
                            MaterialTheme.colorScheme.surface.copy(alpha = 0.78f)
                        )
                    )
                )
        )
        Column(
            modifier = Modifier
                .fillMaxSize()
                .padding(horizontal = 32.dp, vertical = 24.dp)
        ) {
            Row(
                modifier = Modifier.fillMaxWidth(),
                horizontalArrangement = Arrangement.End
            ) {
                BrutalButton(onClick = onDismiss) {
                    Text("EXIT")
                }
            }

            Spacer(modifier = Modifier.height(24.dp))

            if (lines.isEmpty()) {
                Box(
                    modifier = Modifier
                        .fillMaxWidth()
                        .weight(1f),
                    contentAlignment = Alignment.Center
                ) {
                    Text("Load a book to enter focus mode.", color = MaterialTheme.colorScheme.onSurfaceVariant)
                }
            } else {
                LazyColumn(
                    modifier = Modifier
                        .fillMaxWidth()
                        .weight(1f),
                    state = listState,
                    verticalArrangement = Arrangement.spacedBy(18.dp)
                ) {
                    itemsIndexed(lines) { index, line ->
                        ReaderLine(
                            line = line,
                            isSelected = selectedLines.contains(index),
                            isCurrent = index == currentUnitIndex,
                            visuals = visuals,
                            modifier = Modifier.fillMaxWidth(),
                            textStyle = MaterialTheme.typography.titleLarge,
                            textAlign = TextAlign.Start,
                            contentPadding = PaddingValues(vertical = 14.dp, horizontal = 20.dp),
                            shape = RoundedCornerShape(14.dp),
                            onClick = { onLineClick(index) },
                            onLongClick = { onLineLongPress(index) },
                            onDoubleTap = { onLineDoubleTap(index) }
                        )
                    }
                }
            }

            Spacer(modifier = Modifier.height(24.dp))

            Box(
                modifier = Modifier
                    .fillMaxWidth()
                    .background(MaterialTheme.colorScheme.surfaceVariant.copy(alpha = 0.9f), RoundedCornerShape(16.dp))
                    .padding(vertical = 18.dp, horizontal = 12.dp)
            ) {
                WaveformVisualizer(
                    modifier = Modifier.fillMaxWidth(),
                    visible = playerState != PlayerState.IDLE,
                    lineColor = MaterialTheme.colorScheme.primary
                )
            }
        }
    }
}

private data class ReaderLineVisuals(
    val selectedBackground: Color,
    val currentBackground: Color,
    val defaultBackground: Color,
    val selectedText: Color,
    val currentText: Color,
    val defaultText: Color,
)

@Composable
private fun defaultReaderLineVisuals(): ReaderLineVisuals {
    val colorScheme = MaterialTheme.colorScheme
    return ReaderLineVisuals(
        selectedBackground = colorScheme.secondaryContainer,
        currentBackground = colorScheme.primaryContainer,
        defaultBackground = Color.Transparent,
        selectedText = colorScheme.onSecondaryContainer,
        currentText = colorScheme.onPrimaryContainer,
        defaultText = colorScheme.onSurface
    )
}

@Composable
private fun immersiveReaderLineVisuals(): ReaderLineVisuals {
    return ReaderLineVisuals(
        selectedBackground = MaterialTheme.colorScheme.surfaceVariant.copy(alpha = 0.9f),
        currentBackground = MaterialTheme.colorScheme.surfaceVariant.copy(alpha = 0.75f),
        defaultBackground = MaterialTheme.colorScheme.surface.copy(alpha = 0.6f),
        selectedText = MaterialTheme.colorScheme.primary,
        currentText = MaterialTheme.colorScheme.onSurface,
        defaultText = MaterialTheme.colorScheme.onSurfaceVariant
    )
}

@OptIn(ExperimentalFoundationApi::class)
@Composable
private fun ReaderLine(
    line: String,
    isSelected: Boolean,
    isCurrent: Boolean,
    visuals: ReaderLineVisuals,
    modifier: Modifier = Modifier,
    textStyle: TextStyle,
    textAlign: TextAlign = TextAlign.Justify,
    contentPadding: PaddingValues,
    shape: Shape = RectangleShape,
    onClick: () -> Unit,
    onLongClick: () -> Unit,
    onDoubleTap: () -> Unit,
) {
    val background = when {
        isSelected -> visuals.selectedBackground
        isCurrent -> visuals.currentBackground
        else -> visuals.defaultBackground
    }
    val textColor = when {
        isSelected -> visuals.selectedText
        isCurrent -> visuals.currentText
        else -> visuals.defaultText
    }

    Text(
        text = line,
        modifier = modifier
            .combinedClickable(
                onClick = onClick,
                onLongClick = onLongClick,
                onDoubleClick = onDoubleTap
            )
            .background(background, shape)
            .padding(contentPadding),
        color = textColor,
        textAlign = textAlign,
        style = textStyle
    )
}

private fun getDisplayName(context: android.content.Context, uri: Uri): String {
    return context.contentResolver
        .query(uri, arrayOf(OpenableColumns.DISPLAY_NAME), null, null, null)
        ?.use { cursor -> if (cursor.moveToFirst()) cursor.getString(0) else uri.lastPathSegment ?: "document" }
        ?: uri.lastPathSegment ?: "document"
}
