package com.example.nabu.screens

import ai.onnxruntime.OrtSession
import android.content.Intent
import android.net.Uri
import androidx.activity.compose.rememberLauncherForActivityResult
import androidx.activity.result.contract.ActivityResultContracts
import androidx.compose.foundation.ExperimentalFoundationApi
import androidx.compose.foundation.background
import androidx.compose.foundation.clickable
import androidx.compose.foundation.combinedClickable
import androidx.compose.foundation.layout.*
import androidx.compose.foundation.lazy.LazyColumn
import androidx.compose.foundation.lazy.itemsIndexed
import androidx.compose.foundation.lazy.rememberLazyListState
import androidx.compose.material3.*
import androidx.compose.runtime.*
import androidx.compose.ui.Alignment
import androidx.compose.ui.Modifier
import androidx.compose.ui.graphics.Color
import androidx.compose.ui.platform.LocalContext
import androidx.compose.ui.res.dimensionResource
import androidx.compose.ui.text.style.TextAlign
import androidx.lifecycle.viewmodel.compose.viewModel
import com.example.nabu.R
import com.example.nabu.utils.*
import com.example.nabu.ui.components.ProgressDialog
import com.example.nabu.ui.components.RadialWaveformVisualizer
import com.example.nabu.viewmodel.BookViewModel
import kotlinx.coroutines.launch
import com.mewmix.nabu.ui.brutalist.PanelBox
import com.mewmix.nabu.ui.brutalist.BrutalSection
import com.mewmix.nabu.ui.brutalist.Brutal
import com.mewmix.nabu.ui.brutalist.BrutalButton
import com.mewmix.nabu.ui.brutalist.BrutalSlider
import com.mewmix.nabu.ui.brutalist.SwitchToggle
import androidx.compose.ui.unit.dp

@OptIn(ExperimentalMaterial3Api::class, ExperimentalLayoutApi::class, ExperimentalFoundationApi::class)
@Composable
fun BookScreen(
    session: OrtSession,
    phonemeConverter: PhonemeConverter,
    bookViewModel: BookViewModel = viewModel()
) {
    val context = LocalContext.current
    val scope = rememberCoroutineScope()

    val engine by rememberUpdatedState(SettingsManager.getTtsEngine(context))

    LaunchedEffect(engine) {
        kotlinx.coroutines.withContext(kotlinx.coroutines.Dispatchers.IO) {
            OnnxRuntimeManager.initialize(context.applicationContext)
        }
    }

    val playableUnits by bookViewModel.playableUnits.collectAsState()
    val currentUnitIndex by bookViewModel.currentUnitIndex.collectAsState()
    val lines = playableUnits.map { it.text }
    val playerState by bookViewModel.playerState.collectAsState()

    val bookUri by bookViewModel.bookUri.collectAsState()
    var bookmark by remember { mutableStateOf<Bookmark?>(null) }

    val listState = rememberLazyListState()

    val styleLoader = remember { StyleLoader(context) }
    val defaultVoice = styleLoader.names.firstOrNull() ?: "af_sky"
    var selectedStyles by remember { mutableStateOf(listOf(defaultVoice)) }
    var weights by remember { mutableStateOf(mapOf(defaultVoice to 1f)) }
    var interpolationMode by remember { mutableStateOf(InterpolationMode.LINEAR) }
    var speed by remember { mutableFloatStateOf(SettingsManager.getSpeed(context)) }
    var debugMessage by remember { mutableStateOf<String?>(null) }
    var isProcessing by remember { mutableStateOf(false) }
    var isPregenerating by remember { mutableStateOf(false) }
    var preGenProgress by remember { mutableFloatStateOf(0f) }

    var showSettings by remember { mutableStateOf(false) }
    var showProjectSection by remember { mutableStateOf(false) }

    var projectName by remember { mutableStateOf("") }
    var usePregenerated by remember { mutableStateOf(false) }
    var projects by remember { mutableStateOf(listOf<Project>()) }
    val selectedLines = remember { mutableStateListOf<Int>() }
    var followText by remember { mutableStateOf(true) }

    val launcher = rememberLauncherForActivityResult(
        contract = ActivityResultContracts.OpenDocument()
    ) { uri: Uri? ->
        uri?.let {
            // Persist read permission so the URI can be reopened later from saved projects
            context.contentResolver.takePersistableUriPermission(
                it,
                Intent.FLAG_GRANT_READ_URI_PERMISSION
            )
            bookViewModel.openDocument(it)
            bookViewModel.loadBook(context, it)
        }
    }

    LaunchedEffect(Unit) {
        projects = ProjectManager.list(context)
    }

    LaunchedEffect(bookUri) {
        bookUri?.let { uri ->
            val project = ProjectManager.load(context, uri.toString())
            if (project != null) {
                selectedStyles = project.styles.ifEmpty { listOf(defaultVoice) }
                weights = if (project.weights.isNotEmpty()) project.weights else mapOf(defaultVoice to 1f)
                interpolationMode = project.mode
                speed = project.speed
                bookmark = project.bookmark
                 projectName = project.name
                 usePregenerated = project.usePregenerated
                DebugLogger.log("Loaded project: $project")
                bookViewModel.setCurrentUnitIndex(project.bookmark?.line ?: 0)
            } else {
                bookmark = BookmarkManager.load(context, uri.toString())
                DebugLogger.log("Loaded bookmark: $bookmark")
                bookmark?.let { bookViewModel.setCurrentUnitIndex(it.line) } ?: bookViewModel.setCurrentUnitIndex(0)
            }
            projects = ProjectManager.list(context)
        }
    }

    LaunchedEffect(currentUnitIndex, followText) {
        if (followText && currentUnitIndex >= 0) {
            listState.animateScrollToItem(currentUnitIndex)
        }
    }

    LaunchedEffect(playerState) {
        PcmTap.enabled = playerState == PlayerState.PLAYING
    }

    PanelBox(
        modifier = Modifier
            .fillMaxSize()
            .padding(dimensionResource(id = R.dimen.padding_large))
    ) {
        LazyColumn(
            modifier = Modifier.fillMaxSize(),
            verticalArrangement = Arrangement.spacedBy(dimensionResource(id = R.dimen.padding_medium)),
            state = listState
        ) {
        item {
            BrutalSection(
                title = "Settings",
                expanded = showSettings,
                onToggle = { showSettings = !showSettings }
            ) {
                StyleSelector(
                    styleNames = styleLoader.names,
                    selectedStyles = selectedStyles,
                    onAddStyle = { style ->
                        selectedStyles = selectedStyles + style
                        weights = weights + (style to 1f)
                    },
                    onRemoveStyle = { style ->
                        selectedStyles = selectedStyles - style
                        weights = weights - style
                    }
                )
                WeightSliders(
                    selectedStyles = selectedStyles,
                    weights = weights,
                    onWeightChanged = { style, value ->
                        weights = weights.toMutableMap().apply { put(style, value) }
                    }
                )
                InterpolationModeSelector(
                    currentMode = interpolationMode,
                    onModeSelected = { interpolationMode = it }
                )
                Text(
                    "Speed: ${ "%.2f".format(speed)}",
                    style = MaterialTheme.typography.bodyMedium,
                    color = Brutal.textBright
                )
                BrutalSlider(
                    value = speed,
                    onValueChange = { newSpeed ->
                        speed = newSpeed
                        SettingsManager.setSpeed(context, newSpeed)
                    },
                    range = 0.5f..2.0f,
                    modifier = Modifier.fillMaxWidth()
                )
            }
        }

        item {
            BrutalSection(
                title = "Projects",
                expanded = showProjectSection,
                onToggle = { showProjectSection = !showProjectSection }
            ) {
                OutlinedTextField(
                    value = projectName,
                    onValueChange = { projectName = it },
                    label = { Text("Project Name") },
                    modifier = Modifier.fillMaxWidth()
                )
                Row(
                    verticalAlignment = Alignment.CenterVertically,
                    modifier = Modifier.padding(top = dimensionResource(id = R.dimen.padding_small))
                ) {
                    Text("Use Pregenerated", color = Brutal.textBright)
                    Spacer(modifier = Modifier.weight(1f))
                    Switch(checked = usePregenerated, onCheckedChange = { usePregenerated = it })
                }
                Row(
                    horizontalArrangement = Arrangement.spacedBy(dimensionResource(id = R.dimen.padding_small)),
                    modifier = Modifier.padding(top = dimensionResource(id = R.dimen.padding_small))
                ) {
                    BrutalButton(onClick = {
                        bookUri?.let {
                            val project = Project(
                                uri = it.toString(),
                                name = projectName,
                                styles = selectedStyles,
                                weights = weights,
                                mode = interpolationMode,
                                speed = speed,
                                bookmark = bookmark,
                                usePregenerated = usePregenerated
                            )
                            ProjectManager.save(context, project)
                            projects = ProjectManager.list(context)
                        }
                    }) { Text("Save Project") }
                    BrutalButton(onClick = {
                        bookUri?.let {
                            ProjectManager.delete(context, it.toString())
                            projects = ProjectManager.list(context)
                            projectName = ""
                        }
                    }) { Text("Delete Project") }
                }
                if (projects.isNotEmpty()) {
                    Divider(modifier = Modifier.padding(top = dimensionResource(id = R.dimen.padding_small)))
                    Column(modifier = Modifier.padding(top = dimensionResource(id = R.dimen.padding_small))) {
                        projects.forEach { p ->
                            Row(
                                verticalAlignment = Alignment.CenterVertically,
                                modifier = Modifier.fillMaxWidth()
                            ) {
                                Text(p.name, modifier = Modifier.weight(1f), color = Brutal.textBright)
                                BrutalButton(onClick = {
                                    val uri = Uri.parse(p.uri)
                                    bookViewModel.openDocument(uri)
                                    bookViewModel.loadBook(context, uri)
                                }) { Text("Load") }
                                BrutalButton(onClick = {
                                    ProjectManager.delete(context, p.uri)
                                    projects = ProjectManager.list(context)
                                }) { Text("Del") }
                            }
                        }
                    }
                }
            }
        }

        if (bookmark != null && playerState == PlayerState.IDLE) {
            item {
                Row(
                    verticalAlignment = Alignment.CenterVertically,
                    horizontalArrangement = Arrangement.spacedBy(dimensionResource(id = R.dimen.padding_medium))
                ) {
                    Text("Resume at line ${bookmark!!.line + 1}")
                    BrutalButton(onClick = { bookViewModel.setCurrentUnitIndex(bookmark!!.line) }) {
                        Text("Go")
                    }
                    BrutalButton(onClick = {
                        bookUri?.let { BookmarkManager.clear(context, it.toString()) }
                        bookmark = null
                        bookViewModel.setCurrentUnitIndex(-1)
                    }) {
                        Text("Clear")
                    }
                }
            }
        }
        item {
            FlowRow(
                modifier = Modifier.fillMaxWidth(),
                horizontalArrangement = Arrangement.spacedBy(dimensionResource(id = R.dimen.padding_small)),
                maxItemsInEachRow = 3
            ) {
                BrutalButton(onClick = { launcher.launch(arrayOf("text/plain", "application/epub+zip")) }) {
                    Text("Open")
                }
                BrutalButton(
                    onClick = {
                        if (playerState == PlayerState.PLAYING) {
                            bookViewModel.audioPlayer.pause()
                            bookUri?.let {
                                DebugLogger.log("Saving bookmark at line $currentUnitIndex")
                                BookmarkManager.save(context, it.toString(), currentUnitIndex)
                                val project = Project(
                                    uri = it.toString(),
                                    name = projectName,
                                    styles = selectedStyles,
                                    weights = weights,
                                    mode = interpolationMode,
                                    speed = speed,
                                    bookmark = Bookmark(currentUnitIndex),
                                    usePregenerated = usePregenerated
                                )
                                ProjectManager.save(context, project)
                                bookmark = Bookmark(currentUnitIndex)
                            }
                        } else {
                            if (playerState == PlayerState.PAUSED) {
                                bookViewModel.audioPlayer.stop()
                            }
                            bookViewModel.startPlayback(
                                session = session,
                                phonemeConverter = phonemeConverter,
                                styleLoader = styleLoader,
                                selectedStyles = selectedStyles,
                                weights = weights,
                                mode = interpolationMode,
                                speed = speed,
                                units = playableUnits,
                                startUnit = currentUnitIndex.coerceAtLeast(0),
                                bookUri = bookUri,
                                context = context,
                                engine = SettingsManager.getTtsEngine(context),
                                usePregenerated = usePregenerated,
                                onFinished = {
                                    bookUri?.let { u -> BookmarkManager.clear(context, u.toString()) }
                                    bookmark = null
                                },
                            )
                        }
                    },
                    enabled = lines.isNotEmpty()
                ) {
                    Text(
                        when (playerState) {
                            PlayerState.IDLE -> "Play"
                            PlayerState.PLAYING -> "Pause"
                            PlayerState.PAUSED -> "Resume"
                        }
                    )
                }
                BrutalButton(
                    onClick = {
                        bookViewModel.stopPlayback()
                    },
                    enabled = playerState != PlayerState.IDLE
                ) {
                    Text("Stop")
                }
                BrutalButton(
                    onClick = {
                        isProcessing = true
                        scope.launch {
                            try {
                                debugMessage = null
                                val mixedVector = mixStyles(
                                    styleLoader = styleLoader,
                                    styles = selectedStyles,
                                    weights = weights,
                                    mode = interpolationMode
                                )
                                val audioData = mutableListOf<Float>()
                                val engine = SettingsManager.getTtsEngine(context)
                                val sampleRate = if (engine == TtsEngine.KITTEN) 24000 else 22050
                                for (line in lines) {
                                    val (audio, _) = if (engine == TtsEngine.KITTEN) {
                                        val (_, tokens) = KittenPhonemizer.phonemize(line)
                                        createKittenAudioFromStyleVector(
                                            tokens = tokens,
                                            voice = mixedVector,
                                            speed = speed,
                                            session = session
                                        )
                                    } else {
                                        val phonemes = phonemeConverter.phonemize(line)
                                        createAudioFromStyleVector(
                                            phonemes = phonemes,
                                            voice = mixedVector,
                                            speed = speed,
                                            session = session
                                        )
                                    }
                                    audioData.addAll(audio.toList())
                                }
                                val fileName = buildStyleFileName(selectedStyles, weights, interpolationMode)
                                val uri = saveAudio(audioData.toFloatArray(), context, fileName, sampleRate)
                                uri?.let { openAudioFile(context, it) }
                            } catch (e: Exception) {
                                debugMessage = e.localizedMessage
                            } finally {
                                isProcessing = false
                            }
                        }
                    },
                    enabled = lines.isNotEmpty() && !isProcessing
                ) {
                    Text(if (isProcessing) "Saving..." else "Save")
                }
                if (selectedLines.isNotEmpty()) {
                    BrutalButton(
                        onClick = {
                            isProcessing = true
                            scope.launch {
                                try {
                                    debugMessage = null
                                    val mixedVector = mixStyles(
                                        styleLoader = styleLoader,
                                        styles = selectedStyles,
                                        weights = weights,
                                        mode = interpolationMode
                                    )
                                    val audioData = mutableListOf<Float>()
                                    val engine = SettingsManager.getTtsEngine(context)
                                    val sampleRate = if (engine == TtsEngine.KITTEN) 24000 else 22050
                                    for (i in selectedLines.sorted()) {
                                        val (audio, _) = if (engine == TtsEngine.KITTEN) {
                                            val (_, tokens) = KittenPhonemizer.phonemize(lines[i])
                                            createKittenAudioFromStyleVector(
                                                tokens = tokens,
                                                voice = mixedVector,
                                                speed = speed,
                                                session = session
                                            )
                                        } else {
                                            val phonemes = phonemeConverter.phonemize(lines[i])
                                            createAudioFromStyleVector(
                                                phonemes = phonemes,
                                                voice = mixedVector,
                                                speed = speed,
                                                session = session
                                            )
                                        }
                                        audioData.addAll(audio.toList())
                                    }
                                    val fileName = buildStyleFileName(selectedStyles, weights, interpolationMode) + "_clip"
                                    val uri = saveAudio(audioData.toFloatArray(), context, fileName, sampleRate)
                                    uri?.let { openAudioFile(context, it) }
                                    selectedLines.clear()
                                } catch (e: Exception) {
                                    debugMessage = e.localizedMessage
                                } finally {
                                    isProcessing = false
                                }
                            }
                        },
                        enabled = !isProcessing
                    ) {
                        Text(if (isProcessing) "Saving..." else "Save Clip")
                    }
                }
                BrutalButton(
                    onClick = {
                        if (bookUri != null) {
                            isPregenerating = true
                            preGenProgress = 0f
                            scope.launch {
                                try {
                                    val project = Project(
                                        uri = bookUri!!.toString(),
                                        name = projectName,
                                        styles = selectedStyles,
                                        weights = weights,
                                        mode = interpolationMode,
                                        speed = speed,
                                        bookmark = bookmark,
                                        usePregenerated = true
                                    )
                                    preGenerateBook(
                                        context = context,
                                        session = session,
                                        phonemeConverter = phonemeConverter,
                                        styleLoader = styleLoader,
                                        project = project,
                                        lines = lines,
                                        onProgress = { preGenProgress = it }
                                    )
                                    usePregenerated = true
                                    projects = ProjectManager.list(context)
                                } catch (e: Exception) {
                                    debugMessage = e.localizedMessage
                                } finally {
                                    isPregenerating = false
                                }
                            }
                        }
                    },
                    enabled = !isPregenerating && lines.isNotEmpty() && bookUri != null
                ) {
                    Text(if (isPregenerating) "Pre-generating..." else "Pregenerate")
                }
            }
        }

        item {
            SwitchToggle(
                checked = followText,
                onToggle = { followText = it },
                label = "Follow Text"
            )
        }

        item {
            RadialWaveformVisualizer(
                modifier = Modifier
                    .fillMaxWidth()
                    .height(150.dp),
                visible = playerState == PlayerState.PLAYING
            )
        }

        itemsIndexed(lines) { index, line ->
            Text(
                text = line,
                modifier = Modifier
                    .fillMaxWidth()
                    .combinedClickable(
                        onClick = {
                            if (selectedLines.contains(index)) {
                                selectedLines.remove(index)
                            } else {
                                bookViewModel.setCurrentUnitIndex(index)
                                bookViewModel.startPlayback(
                                    session = session,
                                    phonemeConverter = phonemeConverter,
                                    styleLoader = styleLoader,
                                    selectedStyles = selectedStyles,
                                    weights = weights,
                                    mode = interpolationMode,
                                    speed = speed,
                                    units = playableUnits,
                                    startUnit = index,
                                    bookUri = bookUri,
                                    context = context,
                                    engine = SettingsManager.getTtsEngine(context),
                                    usePregenerated = usePregenerated,
                                    onFinished = {
                                        bookUri?.let { u -> BookmarkManager.clear(context, u.toString()) }
                                        bookmark = null
                                    },
                                )
                            }
                        },
                        onLongClick = {
                            if (selectedLines.contains(index)) {
                                selectedLines.remove(index)
                            } else {
                                selectedLines.add(index)
                            }
                        }
                    )
                    .background(
                        when {
                            selectedLines.contains(index) -> MaterialTheme.colorScheme.secondaryContainer
                            index == currentUnitIndex -> MaterialTheme.colorScheme.primaryContainer
                            else -> Color.Transparent
                        }
                    )
                    .padding(dimensionResource(id = R.dimen.padding_small)),
                color = when {
                    selectedLines.contains(index) -> MaterialTheme.colorScheme.onSecondaryContainer
                    index == currentUnitIndex -> MaterialTheme.colorScheme.onPrimaryContainer
                    else -> MaterialTheme.colorScheme.onSurface
                },
                textAlign = TextAlign.Justify,
                style = MaterialTheme.typography.bodyLarge
            )
        }

        item {
            debugMessage?.let {
                Text(
                    text = it,
                    color = MaterialTheme.colorScheme.error,
                    modifier = Modifier.padding(top = dimensionResource(id = R.dimen.padding_medium))
                )
            }
        }

        // Debug logs moved to dedicated screen
    }
    }

    if (isPregenerating) {
        ProgressDialog(
            message = "Pre-generating ${(preGenProgress * 100).toInt()}%",
            progress = preGenProgress
        )
    }
}


